# cmake/summary.cmake — Build configuration summary printed at configure time.
#
# Included at the end of the root CMakeLists.txt.
# All variables it reads must already be set.

# ── helper: print a dep row ───────────────────────────────────────────────────
# Usage: _dep_row("label" "version / path" "note")
macro(_dep_row label ver note)
    message(STATUS "    ${label}  ${ver}  ${note}")
endmacro()

message(STATUS "")
message(STATUS "┌─ ${PROJECT_NAME} v${PROJECT_VERSION} — Build Summary ─────────────────────────")
message(STATUS "│")
message(STATUS "│  CMake      ${CMAKE_VERSION}  (min 3.28)")
message(STATUS "│  Compiler   ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "│  C++        C++${CMAKE_CXX_STANDARD}")
message(STATUS "│  Build      ${CMAKE_BUILD_TYPE}")
message(STATUS "│  bun        ${BUN_EXECUTABLE}")
message(STATUS "│  Frontend   ${FRONTEND_DIST}")
message(STATUS "│")
message(STATUS "│  ── C++ library deps (all fetched by FetchContent / CPM) ───────────────────")
message(STATUS "│")
message(STATUS "│    saucer              v8.0.5    webview + window + app lifecycle")
message(STATUS "│    saucer::desktop     v4.2.0    file/folder picker dialog")
message(STATUS "│    saucer::systray     local     system-tray icon (external/modules/systray)")
message(STATUS "│    saucer::updater     local     auto-updater via libcurl (external/modules/updater)")
message(STATUS "│    saucer::model_dl    local     NLP model download via libcurl")
message(STATUS "│    nlp_engine          local     NLP core + ONNX Runtime (external/nlp)")
message(STATUS "│    onnxruntime         fetched   ML inference backend")
message(STATUS "│    simdutf             fetched   SIMD UTF-8/16/32 conversion")
message(STATUS "│    glaze               fetched   JSON serialisation (header-only)")
message(STATUS "│    nlohmann/json       fetched   JSON (header-only, saucer dep)")
message(STATUS "│    range-v3            fetched   ranges (header-only, saucer dep)")
message(STATUS "│    coco / lockpp /")
message(STATUS "│      flagpp / polo /")
message(STATUS "│      rebind / ereignis fetched   saucer CPM utility headers")
message(STATUS "│")
message(STATUS "│  ── SQLite ──────────────────────────────────────────────────────────────────")
if(SQLCIPHER_FOUND)
    if(SQLCIPHER_LIBRARIES)
        message(STATUS "│    SQLite3     system SQLCipher  ${SQLCIPHER_LIBRARIES}")
        message(STATUS "│    Encryption  AES-256 [ACTIVE — system SQLCipher]")
    else()
        message(STATUS "│    SQLite3     SQLite3MultipleCiphers v2.3.3  (fetched)")
        message(STATUS "│    Encryption  AES-256 [ACTIVE — sqlite3mc, SQLCipher mode]")
    endif()
else()
    message(STATUS "│    SQLite3     *** detection failed — check cmake/sqlite.cmake ***")
    message(STATUS "│    Encryption  INACTIVE")
endif()
message(STATUS "│")
message(STATUS "│  ── System deps (installed by dev.py deps / CI) ────────────────────────────")
message(STATUS "│    libcurl     system    required by updater + model_downloader")
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(STATUS "│    libwebkitgtk6 system  required by saucer on Linux")
    message(STATUS "│    pkg-config  system    optional, used for SQLCipher detection")
endif()
message(STATUS "│")
message(STATUS "│  Tip: FETCHCONTENT_FULLY_DISCONNECTED=ON  →  reuse cached _deps/ downloads")
message(STATUS "│  Tip: python scripts/dev.py debug --fresh →  wipe cache, keep _deps/")
message(STATUS "│")
message(STATUS "└────────────────────────────────────────────────────────────────────────────")
message(STATUS "")
