/**
 * arrangementToScore.ts
 *
 * Converts AudioTrack[] + optional Arrangement + BPM into a Csound score
 * string ready for offline rendering.
 *
 * Rules:
 *  - If an Arrangement is supplied, sections are played in order, each
 *    section repeating `repeatCount` full sequencer cycles.
 *  - A SectionTrackSlot's mute flag silences that track for that section.
 *  - If a slot has a localCopy, its pattern is used instead of the global track.
 *  - PatchBlock tracks are skipped (they have no Csound equivalent here).
 *  - A `tailSecs` gap (default 1.0) is appended after the last note to let
 *    effects ring out.
 *
 * Loop-marker semantics (returned in RenderPlan):
 *  - loopStart = 0 (always — the pattern begins at t=0)
 *  - loopEnd   = total content duration before the tail
 *    (i.e. the point at which the loop would restart)
 *
 * NOTE: Types are defined inline to avoid cross-package imports from react-client.
 * They must remain structurally compatible with the real AudioTrack / Arrangement
 * types in packages/react-client/src/types/.
 */

import { SEQ_INSTR_NAME } from './sequencerInstruments';

// ── Minimal type copies (structurally compatible with react-client types) ─────

interface AudioNote {
  id:       string;
  time:     number;   // step index
  velocity: number;
}

interface AudioTrack {
  id:             string;
  instrument:     string;
  notes:          AudioNote[];
  length:         number;
  rootNote?:      string;
  octaveOffset?:  number;
  schedulerMuted: boolean;
}

interface SectionTrackSlot {
  trackId:    string;
  mute:       boolean;
  localCopy?: AudioTrack;
}

interface ArrangementSection {
  id:          string;
  name:        string;
  repeatCount: number;
  trackSlots:  SectionTrackSlot[];
}

interface Arrangement {
  sections:        ArrangementSection[];
  loopArrangement: boolean;
}

// ── Pitch helpers ─────────────────────────────────────────────────────────────

const NOTE_NAMES = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'] as const;

function noteToMidi(name: string, octave: number): number {
  const i = (NOTE_NAMES as readonly string[]).indexOf(name);
  return i >= 0 ? (octave + 1) * 12 + i : 60;
}

function midiToHz(midi: number): number {
  return 440 * 2 ** ((midi - 69) / 12);
}

// ── Public types ──────────────────────────────────────────────────────────────

export interface RenderPlan {
  /** Csound score string (f-statements + i-events + e-statement). */
  score:      string;
  /** Total CSD duration including tail (seconds). */
  totalSecs:  number;
  /** Loop start in seconds (always 0). */
  loopStart:  number;
  /** Loop end in seconds (content end, before tail). */
  loopEnd:    number;
  /** Sample rate used — caller should match CSD header. */
  sr:         number;
}

// ── Main function ─────────────────────────────────────────────────────────────

export function arrangementToScore(
  globalTracks: AudioTrack[],
  arrangement:  Arrangement | null,
  bpm:          number,
  tailSecs = 1.0,
  sr       = 48000,
): RenderPlan {
  const secPerStep = 60 / bpm / 4;   // one 16th-note step

  const lines: string[] = [
    '; Generated by Syngrafo offline renderer',
    `; BPM=${bpm}  secPerStep=${secPerStep.toFixed(6)}`,
    'f 1 0 4096 10 1',               // sine wave table for SeqSine
  ];

  let cursor  = 0;   // running absolute time in seconds
  let loopEnd = 0;

  const emitSection = (tracks: AudioTrack[], mutedIds: Set<string>): number => {
    const maxLen   = Math.max(...tracks.map(t => t.length), 1);
    const cycleDur = maxLen * secPerStep;

    for (const track of tracks) {
      if (mutedIds.has(track.id)) continue;
      const instrName = SEQ_INSTR_NAME[track.instrument];
      if (!instrName) continue;                // PatchBlock or unknown → skip

      const octave = 4 + (track.octaveOffset ?? 0);
      const hz     = midiToHz(noteToMidi(track.rootNote ?? 'C', octave));
      const vel    = 0.8;                      // default loudness

      for (const note of track.notes) {
        const stepInCycle = note.time % track.length;
        const absTime     = cursor + stepInCycle * secPerStep;
        const dur         = secPerStep * 0.75;
        lines.push(
          `i "${instrName}" ${absTime.toFixed(5)} ${dur.toFixed(5)} ${hz.toFixed(3)} ${vel.toFixed(3)}`,
        );
      }
    }
    return cycleDur;
  };

  if (arrangement && arrangement.sections.length > 0) {
    for (const section of arrangement.sections) {
      for (let rep = 0; rep < section.repeatCount; rep++) {
        // Build effective track list for this section
        const effectiveTracks: AudioTrack[] = [];
        const mutedIds = new Set<string>();

        for (const slot of section.trackSlots) {
          if (slot.mute) { mutedIds.add(slot.trackId); continue; }
          const globalTrack = globalTracks.find(t => t.id === slot.trackId);
          if (!globalTrack) continue;
          effectiveTracks.push(slot.localCopy ?? globalTrack);
        }

        const cycleDur = emitSection(effectiveTracks, mutedIds);
        cursor += cycleDur;
      }
    }
    loopEnd = cursor;
  } else {
    // No arrangement: render all unmuted tracks once (one full cycle)
    const activeTracks = globalTracks.filter(t => !t.schedulerMuted);
    const mutedIds     = new Set<string>();
    const cycleDur     = emitSection(activeTracks, mutedIds);
    loopEnd            = cycleDur;
    cursor             = cycleDur;
  }

  const totalSecs = cursor + tailSecs;
  lines.push(`e ${totalSecs.toFixed(5)}`);

  return {
    score:     lines.join('\n'),
    totalSecs,
    loopStart: 0,
    loopEnd,
    sr,
  };
}
